### ISSUE TITLE
addGroupingPolicy API interface bug

### ISSUE THREAD

**Issue by mynameisny** [casbin/jcasbin#312] opened 2022-11-07 15:37 UTC
When using this interface enforcer. addGroupingPolicy ("member", "group") to add user to an group, occured java.lang.NullPointerException:

### dependencies pom
```xml
<dependency>
    <groupId>org.casbin</groupId>
    <artifactId>jcasbin</artifactId>
    <version>1.31.1</version>
</dependency>

<dependency>
    <groupId>org.casbin</groupId>
    <artifactId>jdbc-adapter</artifactId>
    <version>2.3.3</version>
</dependency>
```

### model.conf
```config
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

### Application
```java
JDBCAdapter adapter = new JDBCAdapter(driver, url, username, password);
String modelPath = "src/main/resources/cabin/model.conf";

Enforcer enforcer = new Enforcer(modelPath, adapter);

enforcer.addPolicy("admin", "/books", "READ");
boolean policy = enforcer.addGroupingPolicy("tony", "admin");  // Exception in thread "main" java.lang.NullPointerException

```

**Comment by imp2002** [comment] 2022-11-07 16:08
verified

**Comment by imp2002** [comment] 2022-11-08 10:07
I took a look and found that this is not a bug, acutrally `addGroupingPolicy()` is a role inheritance, so in `model.conf` should include a `[role_definition]` just look like follows.

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Comment by hsluoyz** [comment] 2022-11-08 15:35
Closed as resolved

**Closed by hsluoyz** 2022-11-08 15:35 UTC
Labels: invalid

**Comment by mynameisny** [comment] 2022-11-10 01:02
Thank you very much! @hsluoyz
