### ISSUE TITLE
Not able to use loadFilteredPolicy with JdbcAdatper in Jcasbin 

### ISSUE THREAD

**Issue by shreyasGit** [casbin/jcasbin#128] opened 2021-01-27 12:24 UTC
i think theres an issue in Jcasbin java version 1.6.3 and older , it does not support filtering on jdbc adapter, when i try to use https://github.com/jcasbin/casbin-spring-boot-starter with jcasbin, i see that in CoreEnforcer , it expects FilterAdapter only from file_adapter package, else throws this eroor.in short cannot use any jdbc adapter with Jcasbin 

```java
* loadFilteredPolicy reloads a filtered policy from file/database.
 *
 * @param filter the filter used to specify which type of policy should be loaded.
 */
public void loadFilteredPolicy(Object filter) {
    model.clearPolicy();
    FilteredAdapter filteredAdapter;
    if (adapter instanceof FilteredAdapter) {
        filteredAdapter = (FilteredAdapter) adapter;
    } else {
        throw new CasbinAdapterException("Filtered policies are not supported by this adapter.");
    }
```

in above code FilteredAdapter  should be referenced from org.casbin.jcasbin.persist package which is a parent interface.
Due to this when i try to use any jdbcadapter to filter policies i get an error "Filtered policies are not supported by this adapter."

**Comment by hsluoyz** [comment] 2021-01-27 12:45
@shy1st plz take a look.

**Comment by hsluoyz** [comment] 2021-01-28 08:53
@shreyasGit fixed and released: https://github.com/casbin/jcasbin/releases/tag/v1.6.4

**Comment by shreyasGit** [comment] 2021-02-02 06:38
this is not fixednow i get following error
Exception in thread "main" java.lang.ClassCastException: org.casbin.adapter.JdbcAdapter cannot be cast to org.casbin.jcasbin.persist.file_adapter.FilteredAdapter
	at org.casbin.jcasbin.main.CoreEnforcer.loadFilteredPolicy(CoreEnforcer.java:241)
	at com.sas.mkt.example.controller.DumpDataUtil.main(DumpDataUtil.java:58)
	
	  if (adapter instanceof org.casbin.jcasbin.persist.FilteredAdapter) {
            filteredAdapter = (FilteredAdapter) adapter;

the cast is not needed

**Comment by shy1st** [comment] 2021-02-02 06:50
@shreyasGit Would you mind show me your code of how you create the JdbcAdapter?

**Comment by hsluoyz** [comment] 2021-02-05 06:24
ping @shreyasGit

**Comment by hsluoyz** [comment] 2021-02-07 13:04
@shreyasGit @shy1st I think I found the cause.

The latest version of casbin-spring-boot-starter was released 15 days ago: https://github.com/jcasbin/casbin-spring-boot-starter/releases/tag/0.0.11

However, latest jCasbin was released 10 days ago: https://github.com/casbin/jcasbin/releases/tag/v1.6.4

So we need to update casbin-spring-boot-starter's POM dependency to use jCasbin v1.6.4. @shy1st can you make a PR for it?

**Comment by shy1st** [comment] 2021-02-07 13:09
@hsluoyz yes,I can.

**Comment by shy1st** [comment] 2021-02-09 08:58
> @shreyasGit @shy1st I think I found the cause.
> 
> The latest version of casbin-spring-boot-starter was released 15 days ago: https://github.com/jcasbin/casbin-spring-boot-starter/releases/tag/0.0.11
> 
> However, latest jCasbin was released 10 days ago: https://github.com/casbin/jcasbin/releases/tag/v1.6.4
> 
> So we need to update casbin-spring-boot-starter's POM dependency to use jCasbin v1.6.4. @shy1st can you make a PR for it?

@hsluoyz Please see: https://github.com/jcasbin/casbin-spring-boot-starter/pull/26

**Comment by hsluoyz** [comment] 2021-02-09 13:18
@shy1st merged, plz make a new release of https://github.com/jcasbin/casbin-spring-boot-starter

**Comment by hsluoyz** [comment] 2021-02-10 06:17
@shreyasGit can you see if v0.0.12 fixed this issue? https://github.com/jcasbin/casbin-spring-boot-starter/releases/tag/0.0.12

**Comment by shy1st** [comment] 2021-02-11 03:30
The v0.0.12 of the casbin-spring-boot-starter had released in the maven repository.

**Closed** 2021-02-11 06:37 UTC
Labels: bug

**Comment by hsluoyz** [comment] 2021-03-07 07:43
@shreyasGit fixed in: https://github.com/casbin/jcasbin/pull/153
